### ISSUE TITLE
Prism is broken with the latest nokogiri release

### ISSUE THREAD

**Issue by taazza** [mwunsch/prism#5]
/home/test_prism/vendor/gems/ruby/1.8/gems/prism-0.1.0/lib/prism/microformat/hcard.rb:60:in `[]': can't convert String into Integer (TypeError)
    from /home/test_prism/vendor/gems/ruby/1.8/gems/prism-0.1.0/lib/prism/microformat/hcard.rb:60
    from /home/test_prism/vendor/gems/ruby/1.8/gems/prism-0.1.0/lib/prism.rb:102:in`call'
    from /home/test_prism/vendor/gems/ruby/1.8/gems/prism-0.1.0/lib/prism.rb:102:in `extract_from'
    from /home/test_prism/vendor/gems/ruby/1.8/gems/prism-0.1.0/lib/prism.rb:109:in`parse'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `collect'
    from /home/test_prism/vendor/gems/ruby/1.8/gems/nokogiri-1.4.2/lib/nokogiri/xml/node.rb:402:in`call'
    from /home/test_prism/vendor/gems/ruby/1.8/gems/nokogiri-1.4.2/lib/nokogiri/xml/node.rb:402:in `each'
    from /home/test_prism/vendor/gems/ruby/1.8/gems/nokogiri-1.4.2/lib/nokogiri/xml/node.rb:401:in`each'
    from /home/test_prism/vendor/gems/ruby/1.8/gems/prism-0.1.0/lib/prism.rb:109:in `collect'
    from /home/test_prism/vendor/gems/ruby/1.8/gems/prism-0.1.0/lib/prism.rb:109:in`parse'
    from /home/test_prism/vendor/gems/ruby/1.8/gems/prism-0.1.0/lib/prism/posh/base.rb:144:in `get_properties'
    from /home/test_prism/vendor/gems/ruby/1.8/gems/prism-0.1.0/lib/prism/posh/base.rb:140:in`each_pair'
    from /home/test_prism/vendor/gems/ruby/1.8/gems/prism-0.1.0/lib/prism/posh/base.rb:140:in `get_properties'
    from /home/test_prism/vendor/gems/ruby/1.8/gems/prism-0.1.0/lib/prism/posh/base.rb:175:in`to_h'
    from /home/test_prism/vendor/gems/ruby/1.8/gems/prism-0.1.0/lib/prism/posh/base.rb:195:in `empty?'
    from /home/test_prism/vendor/gems/ruby/1.8/gems/prism-0.1.0/lib/prism/posh/base.rb:148:in`get_properties'
    from /home/test_prism/vendor/gems/ruby/1.8/gems/prism-0.1.0/lib/prism/posh/base.rb:147:in `reject'
    from /home/test_prism/vendor/gems/ruby/1.8/gems/prism-0.1.0/lib/prism/posh/base.rb:147:in`get_properties'
    from /home/test_prism/vendor/gems/ruby/1.8/gems/prism-0.1.0/lib/prism/posh/base.rb:175:in `to_h'
    from /home/test_prism/vendor/gems/ruby/1.8/gems/prism-0.1.0/lib/prism/posh/base.rb:165:in`[]'
    from /home/test_prism/vendor/gems/ruby/1.8/gems/prism-0.1.0/lib/prism/posh/base.rb:92:in `fn'
    from /home/test_prism/vendor/gems/ruby/1.8/gems/prism-0.1.0/lib/prism/microformat/hcard.rb:99:in`to_vcard'
    from /home/test_prism/vendor/gems/ruby/1.8/gems/prism-0.1.0/bin/prism:95
    from /home/test_prism/vendor/gems/ruby/1.8/gems/prism-0.1.0/bin/prism:80:in `parse_microformats'
    from /home/test_prism/vendor/gems/ruby/1.8/gems/prism-0.1.0/bin/prism:95
    from bin/prism:3:in`load'
    from bin/prism:3

When we instruct Gem bundle to use 1.4.1 everything works fine ;) Might be better off declaring which version of the dependency you need.

**Comment by atd** [comment]
Same problem here, please fix it :-)

**Comment by otobrglez** [comment]
Same problem here. With Ruby 1.8.7-p330 and 1.9.2-p136.

**Comment by ghost** [comment]
Aha. This explains a lot. Spent the last hour or so trying to figure out where I was going wrong. This explains it :-)

The fact that this is still broken after a year is somewhat disturbing. Has anyone made any headway with this?

**Comment by ghost** [comment]
Fixed in my fork. Sent a pull request.

**Comment by josephholsten** [comment]
Could you please merge and release?

**Comment by mwunsch** [comment]
Merged, but having trouble releasing b/c this gem is real old.

I do have plans for it though. @josephholsten: do you need this gem to be released or can you point to the git repo?

**Comment by josephholsten** [comment]
I'd like a release to complement my webfinger toolkit [discodactyl](https://github.com/josephholsten/discodactyl).

Do you have the time to maintain this? I can certainly help if that's useful.

**Comment by mwunsch** [comment]
Was hoping to rewrite it actually :neutral_face:

**Comment by josephholsten** [comment]
Awesome. If there's anything I can do to keep prism 0.1 on life support while you're rewriting, let me know. mofo is beyond help at this point, so prism really is the best thing around for microformats.

**Comment by mwunsch** [comment]
Well, I merged @Nimlhug's pull request in, but am unable to run the tests and am seeing lots of bundler errors. If you feel like taking over the version 0.1.0 branch of prism and figure out how to lock down the dependencies to have it run easily (in Ruby 1.8.7), I can begin working on a 0.2.0 branch.
